package com.example.jetpack.configuration

enum class CountryCode
constructor(
    val code: String
) {
    // START WITH LETTER "A"
    Afghanistan(code = "AF"),
    AlandIslands(code = "AX"),
    Albania(code = "AL"),
    Algeria(code = "DZ"),
    AmericanSamoa(code = "AS"),
    Andorra(code = "AD"),
    Angola(code = "AO"),
    Anguilla(code = "AI"),
    Antarctica(code = "AQ"),
    AntiguaAndBarbuda(code = "AG"),
    Argentina(code = "AR"),
    Armenia(code = "AM"),
    Aruba(code = "AW"),
    Australia(code = "AU"),
    Austria(code = "AT"),
    Azerbaijan(code = "AZ"),

    // START WITH LETTER "B"
    Bahamas(code = "BS"),
    Bahrain(code = "BH"),
    Bangladesh(code = "BD"),
    Barbados(code = "BB"),
    Belarus(code = "BY"),
    Belgium(code = "BE"),
    Belize(code = "BZ"),
    Benin(code = "BJ"),
    Bermuda(code = "BM"),
    Bhutan(code = "BT"),
    Bolivia(code = "BO"),
    BonaireSintEustatiusAndSaba(code = "BQ"),
    BosniaAndHerzegovina(code = "BA"),
    Botswana(code = "BW"),
    BouvetIsland(code = "BV"),
    Brazil(code = "BR"),
    BritishIndianOceanTerritory(code = "IO"),
    BruneiDarussalam(code = "BN"),
    Bulgaria(code = "BG"),
    BurkinaFaso(code = "BF"),
    Burundi(code = "BI"),

    // START WITH LETTER "C"
    CaboVerde(code = "CV"),
    Cambodia(code = "KH"),
    Cameroon(code = "CM"),
    Canada(code = "CA"),
    CaymanIslands(code = "KY"),
    CentralAfricanRepublic(code = "CF"),
    Chad(code = "TD"),
    Chile(code = "CL"),
    China(code = "CN"),
    ChristmasIsland(code = "CX"),
    CocosKeelingIslands(code = "CC"),
    Colombia(code = "CO"),
    Comoros(code = "KM"),
    CongotheDemocraticRepublic(code = "CD"),
    Congo(code = "CG"),
    CookIslands(code = "CK"),
    CostaRica(code = "CR"),
    Croatia(code = "HR"),
    Cuba(code = "CU"),
    Curacao(code = "CW"),
    Cyprus(code = "CY"),
    Czechia(code = "CZ"),

    // START WITH LETTER "D"
    Denmark(code = "DK"),
    Djibouti(code = "DJ"),
    Dominica(code = "DM"),
    DominicanRepublic(code = "DO"),

    // START WITH LETTER "E"
    Ecuador(code = "EC"),
    Egypt(code = "EG"),
    ElSalvador(code = "SV"),
    EquatorialGuinea(code = "GQ"),
    Eritrea(code = "ER"),
    Estonia(code = "EE"),
    Eswatini(code = "SZ"),
    Ethiopia(code = "ET"),

    // START WITH LETTER "F"
    FalklandIslands(code = "FK"),
    FaroeIslands(code = "FO"),
    Fiji(code = "FJ"),
    Finland(code = "FI"),
    France(code = "FR"),
    FrenchGuiana(code = "GF"),
    FrenchPolynesia(code = "PF"),
    FrenchSouthernTerritories(code = "TF"),

    // START WITH LETTER "G"
    Gabon(code = "GA"),
    Gambia(code = "GM"),
    Georgia(code = "GE"),
    Germany(code = "DE"),
    Ghana(code = "GH"),
    Gibraltar(code = "GI"),
    Greece(code = "GR"),
    Greenland(code = "GL"),
    Grenada(code = "GD"),
    Guadeloupe(code = "GP"),
    Guam(code = "GU"),
    Guatemala(code = "GT"),
    Guernsey(code = "GG"),
    Guinea(code = "GN"),
    GuineaBissau(code = "GW"),
    Guyana(code = "GY"),

    // START WITH LETTER "H"
    Haiti(code = "HT"),
    HeardIslandandMcDonaldIslands(code = "HM"),
    HolySee(code = "VA"),
    Honduras(code = "HN"),
    HongKong(code = "HK"),
    Hungary(code = "HU"),

    // START WITH LETTER "I"
    Iceland(code = "IS"),
    India(code = "IN"),
    Indonesia(code = "ID"),
    Iran(code = "IR"),
    Iraq(code = "IQ"),
    Ireland(code = "IE"),
    IsleofMan(code = "IM"),
    Israel(code = "IL"),
    Italy(code = "IT"),
    IvoryCoast(code = "CI"),

    // START WITH LETTER "J"
    Jamaica(code = "JM"),
    Japan(code = "JP"),
    Jersey(code = "JE"),
    Jordan(code = "JO"),

    // START WITH LETTER "K"
    Kazakhstan(code = "KZ"),
    Kenya(code = "KE"),
    Kiribati(code = "KI"),
    NorthKorea(code = "KP"),
    Korea(code = "KR"),
    Kuwait(code = "KW"),
    Kyrgyzstan(code = "KG"),

    // START WITH LETTER "L"
    Laos(code = "LA"),
    Latvia(code = "LV"),
    Lebanon(code = "LB"),
    Lesotho(code = "LS"),
    Liberia(code = "LR"),
    Libya(code = "LY"),
    Liechtenstein(code = "LI"),
    Lithuania(code = "LT"),
    Luxembourg(code = "LU"),

    // START WITH LETTER "M"
    Macao(code = "MO"),
    Madagascar(code = "MG"),
    Malawi(code = "MW"),
    Malaysia(code = "MY"),
    Maldives(code = "MV"),
    Mali(code = "ML"),
    Malta(code = "MT"),
    MarshallIslands(code = "MH"),
    Martinique(code = "MQ"),
    Mauritania(code = "MR"),
    Mauritius(code = "MU"),
    Mayotte(code = "YT"),
    Mexico(code = "MX"),
    Micronesia(code = "FM"),
    Moldova(code = "MD"),
    Monaco(code = "MC"),
    Mongolia(code = "MN"),
    Montenegro(code = "ME"),
    Montserrat(code = "MS"),
    Morocco(code = "MA"),
    Mozambique(code = "MZ"),
    Myanmar(code = "MM"),

    // START WITH LETTER "N"
    Namibia(code = "NA"),
    Nauru(code = "NR"),
    Nepal(code = "NP"),
    Netherlands(code = "NL"),
    NewCaledonia(code = "NC"),
    NewZealand(code = "NZ"),
    Nicaragua(code = "NI"),
    Niger(code = "NE"),
    Nigeria(code = "NG"),
    Niue(code = "NU"),
    NorfolkIsland(code = "NF"),
    NorthMacedonia(code = "MK"),
    NorthernMarianaIslands(code = "MP"),
    Norway(code = "NO"),

    // START WITH LETTER "O"
    Oman(code = "OM"),

    // START WITH LETTER "P"
    Pakistan(code = "PK"),
    Palau(code = "PW"),
    Palestine(code = "PS"),
    Panama(code = "PA"),
    PapuaNewGuinea(code = "PG"),
    Paraguay(code = "PY"),
    Peru(code = "PE"),
    Philippines(code = "PH"),
    Pitcairn(code = "PN"),
    Poland(code = "PL"),
    Portugal(code = "PT"),
    PuertoRico(code = "PR"),

    // START WITH LETTER "Q"
    Qatar(code = "QA"),

    // START WITH LETTER "R"
    Romania(code = "RO"),
    RussianFederation(code = "RU"),
    Rwanda(code = "RW"),

    // START WITH LETTER "S"
    SaintBarthelemy(code = "BL"),
    SaintHelena(code = "SH"),
    SaintKittsandNevis(code = "KN"),
    SaintLucia(code = "LC"),
    SaintMartin(code = "MF"),
    SaintPierreAndMiquelon(code = "PM"),
    SaintVincentAndTheGrenadines(code = "VC"),
    Samoa(code = "WS"),
    SanMarino(code = "SM"),
    SaoTomeandPrincipe(code = "ST"),
    SaudiArabia(code = "SA"),
    Senegal(code = "SN"),
    Serbia(code = "RS"),
    Seychelles(code = "SC"),
    SierraLeone(code = "SL"),
    Singapore(code = "SG"),
    SintMaarten(code = "SX"),
    Slovakia(code = "SK"),
    Slovenia(code = "SI"),
    SolomonIslands(code = "SB"),
    Somalia(code = "SO"),
    SouthAfrica(code = "ZA"),
    SouthGeorgiaAndTheSouthSandwichIslands(code = "GS"),
    SouthSudan(code = "SS"),
    Spain(code = "ES"),
    SriLanka(code = "LK"),
    Sudan(code = "SD"),
    Suriname(code = "SR"),
    SvalbardAndJanMayen(code = "SJ"),
    Sweden(code = "SE"),
    Switzerland(code = "CH"),
    SyrianArabRepublic(code = "SY"),

    // START WITH LETTER "T"
    TimorLeste(code = "TL"),
    Togo(code = "TG"),
    Tokelau(code = "TK"),
    Tonga(code = "TO"),
    TrinidadAndTobago(code = "TT"),
    Tunisia(code = "TN"),
    Turkey(code = "TR"),
    Turkmenistan(code = "TM"),
    TurksandCaicosIslands(code = "TC"),
    Tuvalu(code = "TV"),

    // START WITH LETTER "U"
    Uganda(code = "UG"),
    Ukraine(code = "UA"),
    UnitedArabEmirates(code = "AE"),
    UnitedKingdom(code = "GB"),
    UnitedStatesOfAmerica(code = "US"),
    Uruguay(code = "UY"),
    Uzbekistan(code = "UZ"),

    // START WITH LETTER "V"
    Vanuatu(code = "VU"),
    VaticanCity(code = "VA"),
    Venezuela(code = "VE"),
    Vietnam(code = "VN"),
    VirginIslandsBritish(code = "VG"),
    VirginIslandsUS(code = "VI"),

    // START WITH LETTER "W"
    WallisandFutuna(code="WF"),
    WesternSahara(code="EH"),

    // START WITH LETTER "Y"
    Yemen(code = "YE"),

    // START WITH LETTER "Z"
    Zambia(code="ZM"),
    Zimbabwe(code="ZW"),

    ;
}